### ISSUE TITLE
Documentation for using Firebase Messaging for Android Push Notifications is not working for me

### ISSUE THREAD

**Issue by TTransmit** [awsdocs/amazon-pinpoint-developer-guide#1]
I wanted to convert the last part of my project from using GCM to using Firebase Messaging, which is Amazon Pinpoint. Google says that GCM will be switched off in 9 months. I can't work out how to switch over Amazon Pinpoint whereas other notification using services provided easy to use migration guides. 

I've tried the documentation in this repo: 
https://github.com/awsdocs/amazon-pinpoint-developer-guide/blob/master/doc-source/mobile-sdk-android-push-fcm.md 

The trouble is that the documentation isn't versioned to the SDK. In 2.6.25, `AWSMobileClient` doesn't have a method `defaultMobileClient()`.  I've tried to work it out from the methods available with autocompletion but I've failed. 

The bits of the documentation about extending `FirebaseInstanceIdService` and `FirebaseMessagingService` do not give enough information about what needs to be done and how to hook these services into your app. 

The Pinpoint documentation website only seems to cover GCM: 
https://docs.aws.amazon.com/aws-mobile/latest/developerguide/add-aws-mobile-push-notifications.html

**Comment by jacowarr** [comment]
Thank you for your feedback. We're researching the Android FCM push examples with the engineering team.

**Comment by TTransmit** [comment]
It looks like this is new. I'll give it a try: https://aws-amplify.github.io/docs/android/push-notifications

**Comment by BrentAtAWS** [comment]
Hi TTransit, 

It looks like you already found the Amplify docs that show how to set up FCM notifications on Pinpoint. Did those docs help you get up and running?

We just updated the Pinpoint developer guide to refer to the Amplify documentation for certain setup tasks, so I'd love to hear more about your experience using the Amplify docs.

Thanks,

Brent @ AWS
