### ISSUE TITLE
No email rendering failure event on docs

### ISSUE THREAD

**Issue by leonardobork** [awsdocs/amazon-pinpoint-developer-guide#10]
Hello,

I need rendering failure events to be streamed to my Kinesis stream.

I am using the javascript SDK with the method `sendMessage`

Also, didn't find anything on the here: 

At https://github.com/awsdocs/amazon-pinpoint-developer-guide/blob/master/doc-source/event-streams-data-email.md

Although there are a few mentions here:
https://docs.aws.amazon.com/pinpoint/latest/developerguide/permissions-stream-email-events-kinesis.html

On Rendereing Failures

Thanks

**Comment by leonardobork** [comment]
Figured it out, can I open a PR for this?

**Comment by marcib-AWS** [comment]
A PR would be great! Thanks for taking the time to submit one!

**Comment by leonardobork** [comment]
PR opened here #11

**Comment by marcib-AWS** [comment]
@leonardobork Thanks again for taking the time to submit a pull request. I'll review and verify the changes with the Amazon Pinpoint engineering team.

**Comment by BrentAtAWS** [comment]
It looks like this content was added to the documentation a while ago, so I'll close this Issue out.
