### ISSUE TITLE
设置电子邮件首选项管理系统

### ISSUE THREAD

**Issue by kimliss** [awsdocs/amazon-pinpoint-developer-guide#15]
目前按官方文档走下来所遇到的问题：

### 问题一：

按照[官方文档](https://docs.aws.amazon.com/zh_cn/pinpoint/latest/developerguide/tutorials-email-prefs-part-7.html)的描述，在电子邮件的正文中，请包含“Unsubscribe (退订)”或“Change your email preferences (更改您的电子邮件首选项)”链接。使用以下 URL 作为链接的目的地， 

![微信截图_20200730144223](https://user-images.githubusercontent.com/7286154/88889604-f4008180-d272-11ea-9283-ea6aa13271d8.png)

创建 message 时，将该 URL 填充到 编辑器会包异常
![微信截图_20200730145121](https://user-images.githubusercontent.com/7286154/88890621-763d7580-d274-11ea-9f85-2c5adad20d0a.png)

### 问题二：
请问 URL 是怎么设置

这样？
```html
<a  href="https://www.example.com/prefs.html?firstName={{User.UserAttributes.FirstName}}&lastName={{User.UserAttributes.LastName}}&email={{Attributes.Email}}&endpointId={{Attributes.EndpointId}}&t1={{Attributes.SpecialOffersOptStatus}}&t2={{Attributes.NewProductsOptStatus}}&t3={{Attributes.ComingSoonOptStatus}}&t4={{Attributes.DealOfTheDayOptStatus}}">Unsubscribe (退订)<a/>
```

还是这样？
```html
<a  href="https://www.example.com/prefs.html?firstName=Carlos&lastName=Salazar&email=recipient%40example.com&endpointId=12345">Unsubscribe (退订)<a/>

```

**Comment by BrentAtAWS** [comment]
This section of the Pinpoint documentation has been removed, so I'm closing this Issue. However, there is an official AWS Solution that provides better functionality than the solution that was originally described in this document. See https://aws.amazon.com/solutions/implementations/amazon-pinpoint-preference-center/ for more information.
