### ISSUE TITLE
Send message to Viber

### ISSUE THREAD

**Issue by efuellas** [awsdocs/amazon-pinpoint-developer-guide#16]
Hi.

I'm figuring out how to use Viber as a messaging channel. Hoping someone can help.

Thank you so much.

**Comment by BrentAtAWS** [comment]
You can use Pinpoint's custom channel capability to interact with Viber's API. 

For more information about custom channels in Amazon Pinpoint, see https://docs.aws.amazon.com/pinpoint/latest/developerguide/channels-custom.html.

For more information about the Viber API, see https://developers.viber.com/docs/api/rest-bot-api/.
