### ISSUE TITLE
AWS docs not in-sync with github repo

### ISSUE THREAD

**Issue by jackmcguire1** [awsdocs/amazon-pinpoint-developer-guide#18]
Hi 

it appears the pinpoint campaigns ARN on [official docs website](https://docs.aws.amazon.com/pinpoint/latest/developerguide/segments-dynamic.html) is not in sync with what is defined within the segments-dynamic [github repo docs](https://github.com/awsdocs/amazon-pinpoint-developer-guide/blob/master/segments-dynamic.md) this has caused some temporary confusion, why are the official docs not reflecting these changes?

**Comment by stsctta** [comment]
My apologies. There was a switch in personnel and the updates to the developer guide on GitHub fell off the radar, which is on me. The problem has finally been fixed, and an update finally pushed out.
