### ISSUE TITLE
Docs say I can create custom metrics for custom events - where do I view?

### ISSUE THREAD

**Issue by indriotech** [awsdocs/amazon-pinpoint-developer-guide#2]
-- Added comment on wrong account please ignore this one, will comment with correct acc --

**Comment by joshwolff1** [comment]
The documentation says clearly that Pinpoint allows me to to create custom events and add metrics. I have done this and successfully viewed my custom events in Pinpoint. However, I can only see the attributes in the interface.. how can I see the metrics for custom events?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
