### ISSUE TITLE
How are APNS device tokens handled for building Segments?

### ISSUE THREAD

**Issue by lucianthorr** [awsdocs/amazon-pinpoint-developer-guide#20]
I'm missing a very fundamental piece of how APNs work with AWS Pinpoint.
I have defined a APNs channel and can generate Pinpoint events from my iOS device but when I build a segment off of those events, the endpoint ids are not device tokens.  How can I build segments and notify those iOS endpoints without the device token?  I can create an endpoint attribute and save the device token as an attribute but I don't believe I can pivot that data into a notification destination.
The best I can think of is that I save it as an attribute, export the segment, edit the CSV, import the new segment file and then target that new segment.  I'm assuming that's there's a better way.
Any ideas?

**Comment by BrentAtAWS** [comment]
The Address attribute of the endpoint contains the APNs token.
