### ISSUE TITLE
Amazon Pinpoint Documentation Feedback

### ISSUE THREAD

**Issue by bgiorgini** [awsdocs/amazon-pinpoint-developer-guide#22]
**Topic**
http://docs.aws.amazon.com/en_us/pinpoint/latest/developerguide/tutorials-two-way-sms-part-1.html

This guide is asking to enable two-way SMS, but the long code doesn’t support that capability. Is it possible to update the guide to mention the use of a Toll-Free number instead?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
