### ISSUE TITLE
access denied exception for mobiletargeting:GetUserEndpoints

### ISSUE THREAD

**Issue by PaigeRuppel** [awsdocs/amazon-pinpoint-developer-guide#4]
User: arn:aws:iam::{{userinfo}}:user/{{username}} is not authorized to perform: mobiletargeting:GetUserEndpoints on resource: arn:aws:mobiletargeting:

I am using the java sdk to send a push notification to a specific endpoint that I am trying to retrieve via a userId. I am seeing an access denied exception because i do not have authorization to perform mobiletargeting:GetUserEndpoints - I do not see this role anywhere in the documentation? Is this the correct role to add to my IAM user?

**Comment by mateen-hussain** [comment]
I keep seeing this too and these warnings are quite distracting. 

I am using below package versions for my React-native project

```
    "aws-amplify": "^1.1.19",
    "aws-amplify-react-native": "^2.1.7",
```

**Comment by joebologna** [comment]
I figured out where in IAM to make this change. My message looks like this:

> Failed to remove unused endpoints with error: AccessDeniedException: User: arn:aws:sts::xxxxxxxxxxxx:assumed-role/**app-yyyymmddHHMM-authRole**/CognitoIdentityCredentials is not authorized

I was able to fix it by going to the IAM console (https://console.aws.amazon.com/iam/) and performing these steps:

The console has a `Search` function in the upper left. 

- Search for the authRole, i.e. `app-yyyymmddHHMM-authRole`
- Select the `Permissions` tab
- Expand the `pinpoint_amplify_XXXXXXXX policy
- Click on `Edit Policy`
  - Expand `Pinpoint` (it may have 2 warnings about **apps** resource types)
    - Expand `Resources`, on the **apps** row
      - Expand `Actions`, on the **apps** row
        - check the `[x] Any` box
    - Expand `Actions Read`
      - Expand `Read`
        - Select `[x] GetUserEndPoints`
  - Click on the `Review Policy` button (lower right)
    - Expand the `Pinpoint` row

The screen should look like this:

<img width="813" alt="Screenshot 2019-05-16 10 46 41" src="https://user-images.githubusercontent.com/3162103/57868186-1cb06e80-77c8-11e9-9bdb-7df5cd810629.png">

Click `Save`

Restart your app, the warning should go away.

Simple (not).

**Comment by enriqueao** [comment]
maybe is useful this https://docs.aws.amazon.com/pinpoint/latest/developerguide/tutorials-two-way-sms-part-2.html

**Comment by BrentAtAWS** [comment]
Looks like this one has already been answered.
