### ISSUE TITLE
Push Notifications using Amplify + Pinpoint and Cognito

### ISSUE THREAD

**Issue by bonillam** [awsdocs/amazon-pinpoint-developer-guide#6]
Its proving difficult to add push notifications with Pinpoint for my project.  1) We have  set up a cognito user pool. 2) we have our own database which we will filter to select a group of users (SDB)--based on our custom attributes-- so that we can send push notifications to that group triggered by specific events. 3) we want to use cognito ID to match the users of the selected SDB to then pass on to pinpoint so that it can be sent to the GCN or APNs channels.   4) we are doing the logic for selecting the SDB in the back end.  The questions are: a) can you help me with a roadmap for this implementation; b) do you have code examples that would help me with "targeting" a group that was selected given my custom criteria (steps 2 and 3).   the documentation is very light, once you go to your latest products  (amplify+pinpoint).. need a little push to implement your products. 

I found some examples in amplify and here ```https://stackoverflow.com/questions/51543607/aws-amplify-push-notifications-with-react-native```, but these are for the client side, not the backend

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
