### ISSUE TITLE
Conflicting documentation on Step 3 Part 7

### ISSUE THREAD

**Issue by austinwebber** [awsdocs/amazon-pinpoint-developer-guide#8]
I don't know if I'm going crazy from reading this several times, but on Creating Lambda Functions, Step 3, part 7. it says to create an environment variable with a key of AppId.

However, in the example image it shows ProjectId rather than AppId. I'm assuming ProjectId is what you meant.

It's also confusing since I'm running into issues after completing this entire guide multiple times.

**Comment by austinwebber** [comment]
Issue has been resolved by merging.

**Comment by austinwebber** [comment]
@BrentAtAWS Upon reviewing, the issue is still present. Your most recent commit overwrote my change.

**Comment by marcib-AWS** [comment]
@austindwebber Thanks for letting us know. I (re)applied your fix to the file.
